version: '3.8'

services:
  # Application service
  app:
    build:
      context: ..
      dockerfile: config/Dockerfile
    container_name: kairoslms-app
    restart: unless-stopped
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - kairoslms-network

  # Database service
  db:
    image: postgres:15-alpine
    container_name: kairoslms-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - kairoslms-network

networks:
  kairoslms-network:
    driver: bridge

volumes:
  postgres_data: